[package]
name = "mic-on-board"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
cortex-m-rt = "0.7.3"
microbit-v2 = "0.13.0"
nrf52833-hal = "0.16.0"
nrf52833-pac = "0.12.2"
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
